### PR TITLE
Allows AMD.jl v0.5

### PR DESCRIPTION
**Pull request by amontoison**
Is it possible to do a new release after this PR ?
I can't install `LDLFactorizations.jl` and `QDLDL.jl` in the same time.

### CODE REVIEW

**Comment by imciner2** [comment]
Was the sole reason for bumping the AMD.jl version number because of the addition of new methods, or did it also deprecate/change things?

**Comment by amontoison** [comment]
It only added new methods for the `Hermitian` wrapper.

**Comment by imciner2** [comment]
Great. And it looks like the tests have passed, so I will go ahead and mege this. We'll get a release out in the next few days hopefully then.

**Comment by imciner2** [comment]
@amontoison sorry for the delay, I have just tagged and released version 0.2.1 with the updated compat bounds. Hopefully that unblocks the downstream packages.

**Comment by amontoison** [comment]
Thanks @imciner2 !

**Pull request merged**
